/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FieldLabel: typeof import('./src/components/internal/FieldLabel.vue')['default']
    FieldMessage: typeof import('./src/components/internal/FieldMessage.vue')['default']
    HeightTransition: typeof import('./src/components/HeightTransition.vue')['default']
    InputContainer: typeof import('./src/components/internal/InputContainer.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    Notification: typeof import('./src/components/notification/Notification.vue')['default']
    NotificationContainer: typeof import('./src/components/notification/NotificationContainer.vue')['default']
    RAlert: typeof import('./src/components/alert/RAlert.vue')['default']
    RButton: typeof import('./src/components/button/RButton.vue')['default']
    RCheckbox: typeof import('./src/components/checkbox/RCheckbox.vue')['default']
    RInput: typeof import('./src/components/input/RInput.vue')['default']
    RLoading: typeof import('./src/components/loading/RLoading.vue')['default']
    ROption: typeof import('./src/components/select/ROption.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RPagination: typeof import('./src/components/pagination/RPagination.vue')['default']
    RPanel: typeof import('./src/components/tabs/RPanel.vue')['default']
    RPanelItem: typeof import('./src/components/tabs/RPanelItem.vue')['default']
    RPopup: typeof import('./src/components/popup/RPopup.vue')['default']
    RRadio: typeof import('./src/components/radio/RRadio.vue')['default']
    RSelect: typeof import('./src/components/select/RSelect.vue')['default']
    RSelectGroup: typeof import('./src/components/select/RSelectGroup.vue')['default']
    RSelectInput: typeof import('./src/components/select/RSelectInput.vue')['default']
    RSlider: typeof import('./src/components/slider/RSlider.vue')['default']
    RSliderDot: typeof import('./src/components/slider/RSliderDot.vue')['default']
    RSliderTick: typeof import('./src/components/slider/RSliderTick.vue')['default']
    RSwitch: typeof import('./src/components/switch/RSwitch.vue')['default']
    RTab: typeof import('./src/components/tabs/RTab.vue')['default']
    RTabItem: typeof import('./src/components/tabs/RTabItem.vue')['default']
    SelectedItems: typeof import('./src/components/select_prev/SelectedItems.vue')['default']
    SevueIcon: typeof import('./src/components/icons/SevueIcon.vue')['default']
    VNodeRenderer: typeof import('./src/components/VNodeRenderer.vue')['default']
  }
}
