/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CheckboxRoot: typeof import('./src/components/checkbox/CheckboxRoot.vue')['default']
    DropdownContent: typeof import('./src/components/dropdown/DropdownContent.vue')['default']
    DropdownItem: typeof import('./src/components/dropdown/DropdownItem.vue')['default']
    DropdownRoot: typeof import('./src/components/dropdown/DropdownRoot.vue')['default']
    DropdownTrigger: typeof import('./src/components/dropdown/DropdownTrigger.vue')['default']
    FieldLabel: typeof import('./src/components/internal/FieldLabel.vue')['default']
    FieldMessage: typeof import('./src/components/internal/FieldMessage.vue')['default']
    HeightTransition: typeof import('./src/components/HeightTransition.vue')['default']
    InputContainer: typeof import('./src/components/internal/InputContainer.vue')['default']
    Label: typeof import('./src/components/internal/Label.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    Notification: typeof import('./src/components/notification/Notification.vue')['default']
    NotificationContainer: typeof import('./src/components/notification/NotificationContainer.vue')['default']
    PopperContent: typeof import('./src/components/popper/PopperContent.vue')['default']
    PopperReference: typeof import('./src/components/popper/PopperReference.vue')['default']
    PopperRoot: typeof import('./src/components/popper/PopperRoot.vue')['default']
    PopupClose: typeof import('./src/components/popup/PopupClose.vue')['default']
    PopupContent: typeof import('./src/components/popup/PopupContent.vue')['default']
    PopupDescription: typeof import('./src/components/popup/PopupDescription.vue')['default']
    PopupOverlay: typeof import('./src/components/popup/PopupOverlay.vue')['default']
    PopupRoot: typeof import('./src/components/popup/PopupRoot.vue')['default']
    PopupTitle: typeof import('./src/components/popup/PopupTitle.vue')['default']
    RadioRoot: typeof import('./src/components/radio/RadioRoot.vue')['default']
    RAlert: typeof import('./src/components/alert/RAlert.vue')['default']
    RButton: typeof import('./src/components/button/RButton.vue')['default']
    RCheckbox: typeof import('./src/components/checkbox/RCheckbox.vue')['default']
    RDropdown: typeof import('./src/components/dropdown/RDropdown.vue')['default']
    RDropdownItem: typeof import('./src/components/dropdown/RDropdownItem.vue')['default']
    RInput: typeof import('./src/components/input/RInput.vue')['default']
    RLoading: typeof import('./src/components/loading/RLoading.vue')['default']
    ROption: typeof import('./src/components/select/ROption.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RovingFocusItem: typeof import('./src/components/roving-focus/RovingFocusItem.vue')['default']
    RovingFocusRoot: typeof import('./src/components/roving-focus/RovingFocusRoot.vue')['default']
    RPagination: typeof import('./src/components/pagination/RPagination.vue')['default']
    RPanel: typeof import('./src/components/tabs/RPanel.vue')['default']
    RPanelItem: typeof import('./src/components/tabs/RPanelItem.vue')['default']
    RPopup: typeof import('./src/components/popup/RPopup.vue')['default']
    RRadio: typeof import('./src/components/radio/RRadio.vue')['default']
    RSelect: typeof import('./src/components/select/RSelect.vue')['default']
    RSelectGroup: typeof import('./src/components/select/RSelectGroup.vue')['default']
    RSelectInput: typeof import('./src/components/select/RSelectInput.vue')['default']
    RSlider: typeof import('./src/components/slider/RSlider.vue')['default']
    RSliderDot: typeof import('./src/components/slider/RSliderDot.vue')['default']
    RSliderTick: typeof import('./src/components/slider/RSliderTick.vue')['default']
    RSwitch: typeof import('./src/components/switch/RSwitch.vue')['default']
    RTab: typeof import('./src/components/tabs/RTab.vue')['default']
    RTabItem: typeof import('./src/components/tabs/RTabItem.vue')['default']
    SelectedItems: typeof import('./src/components/select_prev/SelectedItems.vue')['default']
    SevueIcon: typeof import('./src/components/icons/SevueIcon.vue')['default']
    TabsIndicator: typeof import('./src/components/tabs/TabsIndicator.vue')['default']
    TabsItem: typeof import('./src/components/tabs/TabsItem.vue')['default']
    TabsRoot: typeof import('./src/components/tabs/TabsRoot.vue')['default']
    VNodeRenderer: typeof import('./src/components/VNodeRenderer.vue')['default']
  }
}
